services:
  database:
    image: mariadb:lts
    container_name: mariadb_qts
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "${MAIL_PORT}:1025"
      - "8025:8025"
    environment:
      - MP_MAX_MESSAGES=50
    restart: unless-stopped

volumes:
  mariadb_data:
